parameters:
#    jason_first.example.class: Jason\FirstBundle\Example

services:
#    jason_first.example:
#        class: %jason_first.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
